apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-app-back-externalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: sample-app-back-secretstore
    kind: ClusterSecretStore
  target:
    name: sample-db-credentials
    creationPolicy: Owner
  data:
  - secretKey: kh-paloma-m01-01-secret-sample-db-user
    remoteRef:
      key: kh-paloma-m01-01-secret-sample-db-user
  - secretKey: kh-paloma-m01-01-secret-sample-db-password
    remoteRef:
      key: kh-paloma-m01-01-secret-sample-db-password