apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: sample-app-back-secretstore
spec:
  provider:
    gcpsm:
      projectID: kh-paloma-m01-01
      auth:
        workloadIdentity:
          clusterLocation: asia-northeast1-a
          clusterName: kh-paloma-m01-01-gke-cluster01
          clusterProjectID: kh-paloma-m01-01
          serviceAccountRef:
            name: external-secrets-sa
            namespace: default
            